"""
FreightIQ Canonical Route Market Engine & Synthetic Series Generator

Provides deterministic route-specific synthetic freight rate histories,
operational indicators (congestion, vessel availability, risk scores), and feature-engineered
time series DataFrames for every calibrated route in FreightIQ.

All data generated by this module is clearly labeled as DEMO SYNTHETIC.
"""

import os
import hashlib
import numpy as np
import pandas as pd
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field

from backend.domain.routes import get_calibrated_routes, resolve_route, ROUTE_MASTER
from backend.features import generate_features

DEFAULT_DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
ROUTE_CSV_PATH = os.path.join(DEFAULT_DATA_DIR, "route_freight_rates.csv")


@dataclass
class RouteMarketProfile:
    route_key: str
    origin_port_id: str
    destination_port_id: str
    origin_name: str
    destination_name: str
    preferred_vessel_class: str = "Panamax"
    distance_nm: Optional[float] = 4500.0
    base_rate_usd: float = 14.50
    volatility_factor: float = 1.00
    seasonality_phase: float = 0.00
    congestion_sensitivity: float = 1.00
    bunker_sensitivity: float = 1.00
    supply_sensitivity: float = 1.00
    data_mode: str = "SYNTHETIC"
    generation_version: str = "v1.0-demo"
    assumption_label: str = "DEMO_ONLY_ASSUMPTION"


# Pre-configured domain profiles for calibrated routes
DEFAULT_ROUTE_PROFILES: Dict[str, RouteMarketProfile] = {
    "AU_HPT -> IN_PDP": RouteMarketProfile(
        route_key="AU_HPT -> IN_PDP", origin_port_id="AU_HPT", destination_port_id="IN_PDP",
        origin_name="Hay Point", destination_name="Paradip", preferred_vessel_class="Capesize",
        distance_nm=4850.0, base_rate_usd=14.50, volatility_factor=1.00, seasonality_phase=0.00,
        congestion_sensitivity=1.10
    ),
    "AU_DBT -> IN_PDP": RouteMarketProfile(
        route_key="AU_DBT -> IN_PDP", origin_port_id="AU_DBT", destination_port_id="IN_PDP",
        origin_name="Dalrymple Bay", destination_name="Paradip", preferred_vessel_class="Capesize",
        distance_nm=4840.0, base_rate_usd=14.40, volatility_factor=1.02, seasonality_phase=0.10,
        congestion_sensitivity=1.08
    ),
    "AU_GLT -> IN_PDP": RouteMarketProfile(
        route_key="AU_GLT -> IN_PDP", origin_port_id="AU_GLT", destination_port_id="IN_PDP",
        origin_name="Gladstone", destination_name="Paradip", preferred_vessel_class="Panamax",
        distance_nm=4900.0, base_rate_usd=14.80, volatility_factor=0.98, seasonality_phase=0.20,
        congestion_sensitivity=1.05
    ),
    "AU_NCW -> IN_PDP": RouteMarketProfile(
        route_key="AU_NCW -> IN_PDP", origin_port_id="AU_NCW", destination_port_id="IN_PDP",
        origin_name="Newcastle", destination_name="Paradip", preferred_vessel_class="Panamax",
        distance_nm=5200.0, base_rate_usd=15.60, volatility_factor=1.10, seasonality_phase=0.40,
        congestion_sensitivity=1.12
    ),
    "AU_PHE -> IN_PDP": RouteMarketProfile(
        route_key="AU_PHE -> IN_PDP", origin_port_id="AU_PHE", destination_port_id="IN_PDP",
        origin_name="Port Hedland", destination_name="Paradip", preferred_vessel_class="Capesize",
        distance_nm=3600.0, base_rate_usd=12.80, volatility_factor=1.15, seasonality_phase=0.30,
        congestion_sensitivity=1.15
    ),
    "AU_DAM -> IN_PDP": RouteMarketProfile(
        route_key="AU_DAM -> IN_PDP", origin_port_id="AU_DAM", destination_port_id="IN_PDP",
        origin_name="Dampier", destination_name="Paradip", preferred_vessel_class="Capesize",
        distance_nm=3550.0, base_rate_usd=12.60, volatility_factor=1.12, seasonality_phase=0.30,
        congestion_sensitivity=1.14
    ),
    "AU_HPT -> IN_VTZ": RouteMarketProfile(
        route_key="AU_HPT -> IN_VTZ", origin_port_id="AU_HPT", destination_port_id="IN_VTZ",
        origin_name="Hay Point", destination_name="Visakhapatnam", preferred_vessel_class="Capesize",
        distance_nm=4620.0, base_rate_usd=13.90, volatility_factor=0.96, seasonality_phase=0.00,
        congestion_sensitivity=0.95
    ),
    "AU_HPT -> IN_GAV": RouteMarketProfile(
        route_key="AU_HPT -> IN_GAV", origin_port_id="AU_HPT", destination_port_id="IN_GAV",
        origin_name="Hay Point", destination_name="Gangavaram", preferred_vessel_class="Capesize",
        distance_nm=4600.0, base_rate_usd=13.80, volatility_factor=0.95, seasonality_phase=0.00,
        congestion_sensitivity=0.92
    ),
    "AU_HPT -> IN_DHM": RouteMarketProfile(
        route_key="AU_HPT -> IN_DHM", origin_port_id="AU_HPT", destination_port_id="IN_DHM",
        origin_name="Hay Point", destination_name="Dhamra", preferred_vessel_class="Capesize",
        distance_nm=4880.0, base_rate_usd=14.65, volatility_factor=1.01, seasonality_phase=0.05,
        congestion_sensitivity=1.00
    ),
    "AU_HPT -> IN_HAL": RouteMarketProfile(
        route_key="AU_HPT -> IN_HAL", origin_port_id="AU_HPT", destination_port_id="IN_HAL",
        origin_name="Hay Point", destination_name="Haldia", preferred_vessel_class="Panamax",
        distance_nm=5100.0, base_rate_usd=15.40, volatility_factor=1.08, seasonality_phase=0.10,
        congestion_sensitivity=1.25
    ),
    "ID_TBN -> IN_PDP": RouteMarketProfile(
        route_key="ID_TBN -> IN_PDP", origin_port_id="ID_TBN", destination_port_id="IN_PDP",
        origin_name="Taboneo", destination_name="Paradip", preferred_vessel_class="Panamax",
        distance_nm=2450.0, base_rate_usd=9.00, volatility_factor=0.88, seasonality_phase=1.00,
        congestion_sensitivity=1.00
    ),
    "ID_BPN -> IN_VTZ": RouteMarketProfile(
        route_key="ID_BPN -> IN_VTZ", origin_port_id="ID_BPN", destination_port_id="IN_VTZ",
        origin_name="Balikpapan", destination_name="Visakhapatnam", preferred_vessel_class="Panamax",
        distance_nm=2200.0, base_rate_usd=8.40, volatility_factor=0.85, seasonality_phase=1.10,
        congestion_sensitivity=0.90
    ),
    "ID_TBN -> IN_HAL": RouteMarketProfile(
        route_key="ID_TBN -> IN_HAL", origin_port_id="ID_TBN", destination_port_id="IN_HAL",
        origin_name="Taboneo", destination_name="Haldia", preferred_vessel_class="Panamax",
        distance_nm=2600.0, base_rate_usd=9.60, volatility_factor=0.92, seasonality_phase=1.00,
        congestion_sensitivity=1.20
    ),
    "ZA_RCB -> IN_PDP": RouteMarketProfile(
        route_key="ZA_RCB -> IN_PDP", origin_port_id="ZA_RCB", destination_port_id="IN_PDP",
        origin_name="Richards Bay", destination_name="Paradip", preferred_vessel_class="Capesize",
        distance_nm=4550.0, base_rate_usd=13.60, volatility_factor=1.05, seasonality_phase=0.70,
        congestion_sensitivity=1.05
    ),
    "ZA_RCB -> IN_VTZ": RouteMarketProfile(
        route_key="ZA_RCB -> IN_VTZ", origin_port_id="ZA_RCB", destination_port_id="IN_VTZ",
        origin_name="Richards Bay", destination_name="Visakhapatnam", preferred_vessel_class="Capesize",
        distance_nm=4400.0, base_rate_usd=13.20, volatility_factor=1.02, seasonality_phase=0.70,
        congestion_sensitivity=0.95
    ),
    "ZA_RCB -> IN_HAL": RouteMarketProfile(
        route_key="ZA_RCB -> IN_HAL", origin_port_id="ZA_RCB", destination_port_id="IN_HAL",
        origin_name="Richards Bay", destination_name="Haldia", preferred_vessel_class="Panamax",
        distance_nm=4750.0, base_rate_usd=14.20, volatility_factor=1.09, seasonality_phase=0.80,
        congestion_sensitivity=1.22
    ),
    "MZ_MNC -> IN_PDP": RouteMarketProfile(
        route_key="MZ_MNC -> IN_PDP", origin_port_id="MZ_MNC", destination_port_id="IN_PDP",
        origin_name="Nacala", destination_name="Paradip", preferred_vessel_class="Panamax",
        distance_nm=3900.0, base_rate_usd=12.30, volatility_factor=0.98, seasonality_phase=0.60,
        congestion_sensitivity=1.02
    ),
    "BR_PDM -> IN_PDP": RouteMarketProfile(
        route_key="BR_PDM -> IN_PDP", origin_port_id="BR_PDM", destination_port_id="IN_PDP",
        origin_name="Ponta da Madeira", destination_name="Paradip", preferred_vessel_class="Capesize",
        distance_nm=11200.0, base_rate_usd=26.80, volatility_factor=1.35, seasonality_phase=1.50,
        congestion_sensitivity=1.15
    ),
    "BR_PDM -> IN_GAV": RouteMarketProfile(
        route_key="BR_PDM -> IN_GAV", origin_port_id="BR_PDM", destination_port_id="IN_GAV",
        origin_name="Ponta da Madeira", destination_name="Gangavaram", preferred_vessel_class="Capesize",
        distance_nm=11150.0, base_rate_usd=26.50, volatility_factor=1.32, seasonality_phase=1.50,
        congestion_sensitivity=1.10
    ),
    "IN_PDP -> IN_MAA": RouteMarketProfile(
        route_key="IN_PDP -> IN_MAA", origin_port_id="IN_PDP", destination_port_id="IN_MAA",
        origin_name="Paradip", destination_name="Chennai", preferred_vessel_class="Supramax",
        distance_nm=650.0, base_rate_usd=3.60, volatility_factor=0.60, seasonality_phase=0.00,
        congestion_sensitivity=0.80
    ),
    "IN_PDP -> IN_VTZ": RouteMarketProfile(
        route_key="IN_PDP -> IN_VTZ", origin_port_id="IN_PDP", destination_port_id="IN_VTZ",
        origin_name="Paradip", destination_name="Visakhapatnam", preferred_vessel_class="Supramax",
        distance_nm=280.0, base_rate_usd=2.20, volatility_factor=0.50, seasonality_phase=0.00,
        congestion_sensitivity=0.75
    ),
    "IN_PDP -> IN_TUT": RouteMarketProfile(
        route_key="IN_PDP -> IN_TUT", origin_port_id="IN_PDP", destination_port_id="IN_TUT",
        origin_name="Paradip", destination_name="Tuticorin", preferred_vessel_class="Supramax",
        distance_nm=820.0, base_rate_usd=4.30, volatility_factor=0.65, seasonality_phase=0.00,
        congestion_sensitivity=0.85
    )
}


def get_route_seed(route_key: str, global_seed: int = 42) -> int:
    """Computes a stable, process-independent deterministic integer seed for any route_key."""
    md5_hex = hashlib.md5(route_key.encode("utf-8")).hexdigest()
    route_int = int(md5_hex[:8], 16)
    return (route_int + global_seed) % (2**31 - 1)


def get_route_market_profile(route_key_or_alias: str) -> RouteMarketProfile:
    """Retrieves or synthesizes a RouteMarketProfile for a route key or alias."""
    if route_key_or_alias in DEFAULT_ROUTE_PROFILES:
        return DEFAULT_ROUTE_PROFILES[route_key_or_alias]

    if " -> " in route_key_or_alias:
        parts = route_key_or_alias.split(" -> ")
        res = resolve_route(parts[0], parts[1])
    else:
        res = resolve_route(route_key_or_alias, "")

    clean_key = res.route_key if res.route_key else route_key_or_alias

    if clean_key in DEFAULT_ROUTE_PROFILES:
        return DEFAULT_ROUTE_PROFILES[clean_key]

    # Synthesize profile if missing
    multiplier = res.base_freight_multiplier if res.base_freight_multiplier else 1.0
    base_usd = round(14.50 * multiplier, 2)
    return RouteMarketProfile(
        route_key=clean_key,
        origin_port_id=res.origin_port_id or "AU_HPT",
        destination_port_id=res.destination_port_id or "IN_PDP",
        origin_name=res.origin_name or "Origin",
        destination_name=res.destination_name or "Destination",
        distance_nm=res.distance_nm or 4500.0,
        base_rate_usd=base_usd,
        volatility_factor=round(0.85 + (abs(hash(clean_key)) % 40) / 100.0, 2)
    )


def generate_all_route_markets(data_dir: str = DEFAULT_DATA_DIR) -> pd.DataFrame:
    """
    Generates long-format synthetic daily freight time series for all calibrated routes.
    Hierarchical synthetic model:
      route_rate_t = base_rate + global_macro_t * volatility_factor + seasonality_t + route_noise_t
    Saved to data/route_freight_rates.csv.
    """
    dates = pd.date_range(start="2024-01-01", end="2026-08-31", freq="D")
    N = len(dates)

    # 1. Global Dry Bulk Latent Factor (Seed 42)
    rng_global = np.random.RandomState(42)
    t = np.arange(N)
    global_macro = (
        2.5 * np.sin(2 * np.pi * t / 365.25) +
        1.2 * np.cos(4 * np.pi * t / 365.25) +
        np.cumsum(rng_global.normal(0, 0.15, size=N))
    )
    # Detrend cumsum to keep macro factor stationary around mean 0
    global_macro = global_macro - np.polyval(np.polyfit(t, global_macro, 1), t)

    # Global BDI and Bunker price factors
    global_bdi = 1500.0 + global_macro * 80.0 + rng_global.normal(0, 15.0, size=N)
    global_bunker = 600.0 + global_macro * 15.0 + rng_global.normal(0, 5.0, size=N)

    calibrated = get_calibrated_routes()
    records = []

    for item in calibrated:
        r_key = item["route_key"]
        profile = get_route_market_profile(r_key)
        seed = get_route_seed(r_key)
        rng_route = np.random.RandomState(seed)

        # Route-specific AR(1) disturbance
        noise = rng_route.normal(0, 0.45 * profile.volatility_factor, size=N)
        ar1_noise = np.zeros(N)
        ar1_noise[0] = noise[0]
        for idx in range(1, N):
            ar1_noise[idx] = 0.82 * ar1_noise[idx - 1] + noise[idx]

        # Route seasonality
        seasonality = 1.5 * np.sin(2 * np.pi * t / 365.25 + profile.seasonality_phase)

        # Compute spot rate
        freight_rate = profile.base_rate_usd + (global_macro * 0.45 * profile.volatility_factor) + seasonality + ar1_noise
        freight_rate = np.maximum(2.50, np.round(freight_rate, 2))

        # Route-specific congestion index
        cong_base = 45.0 + 10.0 * np.sin(2 * np.pi * t / 365.25 + profile.seasonality_phase + 0.5)
        cong_noise = rng_route.normal(0, 4.0 * profile.congestion_sensitivity, size=N)
        congestion_score = np.clip(cong_base + cong_noise, 10.0, 95.0)
        avg_waiting_hours = np.round(congestion_score * 0.55, 1)

        # Vessel availability
        vessel_base = 28.0 + 5.0 * np.cos(2 * np.pi * t / 365.25 + profile.seasonality_phase)
        vessel_noise = rng_route.normal(0, 3.0, size=N)
        vessel_avail = np.clip(np.round(vessel_base + vessel_noise), 5, 75).astype(int)

        # Weather & Event risk
        weather_risk = np.clip(np.round(3.0 + 1.2 * np.sin(2 * np.pi * t / 365.25) + rng_route.normal(0, 0.6, size=N), 1), 1.0, 10.0)
        event_risk = np.clip(np.round(2.0 + rng_route.normal(0, 0.5, size=N), 1), 1.0, 10.0)

        for d_idx in range(N):
            records.append({
                "date": dates[d_idx].strftime("%Y-%m-%d"),
                "route_key": profile.route_key,
                "origin_port_id": profile.origin_port_id,
                "destination_port_id": profile.destination_port_id,
                "freight_rate": freight_rate[d_idx],
                "bdi_context": round(float(global_bdi[d_idx]), 1),
                "bunker_context": round(float(global_bunker[d_idx]), 1),
                "port_congestion_score": round(float(congestion_score[d_idx]), 1),
                "avg_waiting_hours": float(avg_waiting_hours[d_idx]),
                "vessel_availability_count": int(vessel_avail[d_idx]),
                "weather_risk_score": float(weather_risk[d_idx]),
                "event_risk_score": float(event_risk[d_idx]),
                "data_mode": profile.data_mode
            })

    long_df = pd.DataFrame(records)
    os.makedirs(data_dir, exist_ok=True)
    long_df.to_csv(os.path.join(data_dir, "route_freight_rates.csv"), index=False)
    return long_df


_CACHED_ALL_ROUTES_DF: Optional[pd.DataFrame] = None


def get_all_route_market_histories(data_dir: str = DEFAULT_DATA_DIR) -> pd.DataFrame:
    """Loads long-format route market history DataFrame from CSV or generates if missing."""
    global _CACHED_ALL_ROUTES_DF
    csv_path = os.path.join(data_dir, "route_freight_rates.csv")

    if _CACHED_ALL_ROUTES_DF is not None:
        return _CACHED_ALL_ROUTES_DF

    if not os.path.exists(csv_path):
        _CACHED_ALL_ROUTES_DF = generate_all_route_markets(data_dir)
    else:
        _CACHED_ALL_ROUTES_DF = pd.read_csv(csv_path)

    _CACHED_ALL_ROUTES_DF["date"] = pd.to_datetime(_CACHED_ALL_ROUTES_DF["date"])
    return _CACHED_ALL_ROUTES_DF


def get_available_route_keys() -> List[str]:
    """Returns list of all route keys present in canonical route market dataset."""
    df = get_all_route_market_histories()
    return sorted(df["route_key"].unique().tolist())


def get_route_market_history(route_key_or_ports: str, data_dir: str = DEFAULT_DATA_DIR) -> pd.DataFrame:
    """
    Returns feature-engineered DataFrame for a specific route.
    If route is not directly found, resolves route via canonical resolver.
    """
    all_df = get_all_route_market_histories(data_dir)

    target_key = route_key_or_ports
    if target_key not in all_df["route_key"].values:
        if " -> " in route_key_or_ports:
            parts = route_key_or_ports.split(" -> ")
            res = resolve_route(parts[0], parts[1])
        else:
            res = resolve_route(route_key_or_ports, "")
        if res.route_key in all_df["route_key"].values:
            target_key = res.route_key

    route_df = all_df[all_df["route_key"] == target_key].copy()

    # Fallback to AU_HPT -> IN_PDP if target route series absent
    if len(route_df) == 0:
        fallback_key = "AU_HPT -> IN_PDP"
        route_df = all_df[all_df["route_key"] == fallback_key].copy()
        if len(route_df) == 0:
            route_df = all_df.iloc[:974].copy()

    route_df = route_df.sort_values("date").reset_index(drop=True)

    # Attach global commodity prices and macro indices for feature compatibility
    cmd_path = os.path.join(data_dir, "commodity_prices.csv")
    if os.path.exists(cmd_path):
        cmd_df = pd.read_csv(cmd_path)
        cmd_df["date"] = pd.to_datetime(cmd_df["date"])
        route_df = pd.merge(route_df, cmd_df[["date", "coking_coal_price", "iron_ore_price"]], on="date", how="left")
        route_df["coking_coal_price"] = route_df["coking_coal_price"].ffill().bfill().fillna(220.0)
        route_df["iron_ore_price"] = route_df["iron_ore_price"].ffill().bfill().fillna(110.0)
    else:
        route_df["coking_coal_price"] = 220.0
        route_df["iron_ore_price"] = 110.0

    route_df["bdi"] = route_df.get("bdi_context", 1500.0)
    route_df["capesize_index"] = route_df["bdi"] * 1.2
    route_df["panamax_index"] = route_df["bdi"] * 0.9

    # Generate engineered features
    feat_df = generate_features(route_df)
    return feat_df


def get_route_latest_state(route_key_or_ports: str) -> dict:
    """Returns latest observation state dictionary for specified route."""
    df = get_route_market_history(route_key_or_ports)
    latest_row = df.iloc[-1].to_dict()
    latest_row["route_key"] = route_key_or_ports
    return latest_row
